name: Test project

on: 
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs: 
  after_merge:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    environment: dev
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.DEPLOY_HOST }}
      USER: ${{ vars.DEPLOY_USER }}
      PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
      PORT: ${{ secrets.DEPLOY_PORT }}
    steps:
      - name: Debug SSH command
        run: |
          echo "ssh -o StrictHostKeyChecking=no -p \"$PORT\" \"$DEPLOY_USER@$HOST\""
      - name: SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -p $PORT $HOST@$HOST
          yes
          $PASSWORD

          

    
