name: Test project

on: 
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:


    

jobs: 
  after_merge:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    environment: dev
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.DEPLOY_HOST }}
      USER: ${{ vars.DEPLOY_USER }}
      PASSWORD: ${{ vars.DEPLOY_PASSWORD }}
      PORT: ${{ vars.PORT }}

    steps:
        - name: wypisanie
          run: ${{ env.PORT }}

        - name: SSH connection
          run:
            ssh ${{ env.USER }} '@' ${{ env.HOST }} '-p' ${{ env.PORT }} 
            ${{  env.PASSWORD }}
